import asyncio
import random

# FIXME: CAN I READ FROM STDIN?
# FIXME: CAN THE OUTSIDE SEND TO STDIN?
# FIXME: READ FROM STDOUT
# FIXME: WRITE TO  STDOUT
# FIXME: DOES THE CHILD PROCESS NEED TO BE `asyncio` AS WELL?